const SCROLL_SPEED = 10;
const OBSTICLE_SIZE = 75;
const GROUND_HEIGHT = 100;
const PLAYER_SIZE = 75;
const PLAYER_X = 75;
const GRAVITY = -1; //pixels per frame
const JUMP_VELOCITY = 20;
const GAME_HEIGHT = window.innerHeight;
const GAME_WIDTH = GAME_HEIGHT * 16/9
const FPS = 60